tuna/opentuna

lib/web-portal.ts

feat: use one target group for web portal requests

---

lib/web-portal.ts

feat: specify fargate 1.4 explicitly in web portal service

---

lib/mirror-config.ts

chore: change upstream of alpine to bfsu

---

web-portal/Dockerfile
web-portal/_config.yml
web-portal/nginx.conf

Improve web portal

---

lib/mirror-config.ts
package-lock.json
package.json
test/tuna-worker.test.ts

fix: won't follow links of debian mirror as workaround for EFS hard links limitation

---

web-portal/_config.yml

fix: fix url in pypi help

---

.gitmodules
web-portal/Dockerfile

feat: track opentuna-site revision as submodule

---

lib/content-server.ts
lib/opentuna-stack.ts
test/content-server.test.ts
test/opentuna.test.ts

Cloudwatch dashboard

---

lib/mirror-config.ts
test/tuna-worker.test.ts
web-portal/Dockerfile

feat: add archlinux{,cn,arm} repos

---

README.md
lib/mirror-config.ts
lib/monitor-stack.ts
lib/opentuna-stack.ts
package-lock.json
package.json
test/monitor.test.ts

feat: run periodic codebuild to test availability of several repos

---

web-portal/Dockerfile

feat: enable rubygems help and use its help link in index page

---

lib/mirror-config.ts

feat: setup centos mirror in elrepo tester

---

lib/mirror-config.ts
test/tuna-worker.test.ts
web-portal/Dockerfile

Upon request of https://github.com/tuna/issues/issues/960

feat: add linuxmint repo and refactor tests

---

content-server/nginx.conf

Based on community user feedback, add special handling for archlinux.

feat: add cache policy for pacman index files

---

lib/lambda.d/slack-webhook/index.py
lib/pipeline-stack.ts

feat: send notification when pipeline status is changed

---

README.md
lib/certificate-stack.ts
lib/lambda.d/cert-renew-scheduler/index.ts
lib/lambda.d/cert-renew-scheduler/package-lock.json
lib/lambda.d/cert-renew-scheduler/package.json
lib/lambda.d/iam-cert-event-sender/index.ts
lib/lambda.d/iam-cert-event-sender/package-lock.json
lib/lambda.d/iam-cert-event-sender/package.json
lib/lambda.pipelines.d/stage-conf-updator/index.ts
lib/lambda.pipelines.d/stage-conf-updator/package-lock.json
lib/lambda.pipelines.d/stage-conf-updator/package.json
lib/opentuna-stack.ts
lib/pipeline-stack.ts
package.json
pipeline.md
test/certificate.test.ts
test/opentuna.test.ts

add auto renew certificate capability

---

lib/monitor-stack.ts
test/monitor.test.ts

feat: use nwcd mirror for docker image in monitor stack

---

lib/mirror-config.ts
web-portal/Dockerfile

feat: sync apache projects

---

lib/mirror-config.ts
web-portal/Dockerfile

And add Hugging Face Model Hub

fix: remove git repos that cannot be distributed by opentuna

---

lib/mirror-config.ts
web-portal/Dockerfile

For https://github.com/tuna/issues/issues/1098.

feat: add raspbian and raspberrypi

---

lib/pipeline-stack.ts
test/pipeline.test.ts

chore: disable full request logging to mitigate the concerns of leaking

---

lib/mirror-config.ts
web-portal/Dockerfile
web-portal/_config.yml

fix: add missing jekyll config and remove stale git link

---

lib/analytics-stack.ts
lib/certificate-stack.ts
lib/pipeline-stack.ts
test/analytics.test.ts
test/pipeline.test.ts

Fix #182 by bumping nodejs to 14

chore: nodejs 12 is EOL, bump to 14

---

lib/pipeline-stack.ts
test/pipeline.test.ts

https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html#linux-runtimes

fix: correct codebuild env that contains nodejs 14

---

lib/mirror-config.ts

TUNA no longer provides these repos.

chore: switch julia and sagemath upstream

---

README.md

Sometimes we have to say goodbye (at least for now).

README: sadly announcing the sunset of OpenTUNA
